name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start Couchbase
      run: |
        docker run -t --name db -p 8091-8094:8091-8094 -p 11210:11210 couchbase/server-sandbox:6.5.0 &
        sleep 60
        docker exec -it db couchbase-cli bucket-create --username Administrator --password password --bucket feathers-test --bucket-type memcached --bucket-ramsize 100 --cluster localhost
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
